### ISSUE TITLE
v0.9.8-r11 - radarr/lidarr/sonarr errors

### ISSUE THREAD

**Issue by lethargynavigator** [jesec/rtorrent#16]
After updating to 0.9.8-r11 I'm seeing errors in the event logs of radarr/lidarr/sonarr, which I have rtorrent configured as a download client.

The download is successful, but this error is returned:
```
Message
Request Failed. POST /api/v1/release: response contains array value where integer expected [response]
Exception
CookComputing.XmlRpc.XmlRpcTypeMismatchException: response contains array value where integer expected [response]
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseArray(XmlNode node, Type valueType, ParseStack parseStack, MappingAction mappingAction)
   at CookComputing.XmlRpc.XmlRpcSerializer.ParseValue(XmlNode node, Type valueType, ParseStack parseStack, MappingAction mappingAction, Type& parsedType, Type& parsedArrayType)
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(XmlDocument xdoc, Type returnType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
   at XmlRpcProxy590c83ef-700c-4d42-b1df-23a767d96ef8.LoadRawStart(String target, Byte[] data, String[] commands)
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.<>c__DisplayClass5_0.<AddTorrentFromFile>b__0() in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 152
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.ExecuteRequest[T](Func`1 task) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 259
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.AddTorrentFromFile(String fileName, Byte[] fileContent, String label, RTorrentPriority priority, String directory, RTorrentSettings settings) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrentProxy.cs:line 142
   at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.AddFromTorrentFile(RemoteAlbum remoteAlbum, String hash, String filename, Byte[] fileContent) in D:\a\1\s\src\NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs:line 86
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteAlbum remoteAlbum, String torrentUrl) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 190
   at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 122
   at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteAlbum remoteAlbum) in D:\a\1\s\src\NzbDrone.Core\Download\DownloadService.cs:line 74
   at Lidarr.Api.V1.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in D:\a\1\s\src\Lidarr.Api.V1\Indexers\ReleaseModule.cs:line 124
   at Lidarr.Api.V1.Indexers.ReleaseModule.<.ctor>b__10_0(Object x) in D:\a\1\s\src\Lidarr.Api.V1\Indexers\ReleaseModule.cs:line 57
   at Nancy.NancyModule.<>c__DisplayClass38_0`1.<Post>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass40_0`1.<Post>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

**Comment by lethargynavigator** [comment]
No longer seeing the issue in r12 - thanks for the quick fix
